apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    app: c-http-server
    test_id: {{ .Values.testId }}
    runtime_class: {{ .Values.runtimeClassName }}
    variant: {{ .Values.variant }}
spec:
  type: ClusterIP
  selector:
    app: c-http-server
    test_id: {{ .Values.testId }}
    runtime_class: {{ .Values.runtimeClassName }}
    variant: {{ .Values.variant }}
  ports:
    - port: {{ .Values.servicePort }}
      targetPort: {{ .Values.servicePort }}
